### ISSUE TITLE
Babel 7 Support

### ISSUE THREAD

**Issue by johnsoncode** [vacuumlabs/babel-plugin-extensible-destructuring#28]
Is there a plan to support Babel 7? I get errors when I upgrade to Babel 7 and try to continue to use this plugin.

**Comment by hleumas** [comment]
Thanks for question. This commit: https://github.com/vacuumlabs/babel-plugin-extensible-destructuring/commit/4f8860856146a1b47dfcd349f8c7c5d965839c0a

was supposed to fix that, maybe it didn't. @palnes can you help please?

**Comment by johnsoncode** [comment]
I'm actually going to close this because, now I can't reproduce the issue I was having before. Thanks for the quick response though! Appreciate it!
