### ISSUE TITLE
Enabling plugin causes output of `let` keywords

### ISSUE THREAD

**Issue by hleumas** [vacuumlabs/babel-plugin-extensible-destructuring#3]
```es6
// example.js
const a = 5
```
Running
`node_modules/babel/bin/babel.js example.js`

Results in:
```
"use strict";

let a = 4;
```

Instead of:
```
"use strict";

var a = 4;
```

**Comment by TheMarketka** [comment]
Found the cause. The output of `let` happens when the plugin is ran _before_ the internal ones, but when it is specified with `:after`, it outputs `var`. Will update tests and README accordingly.
