### ISSUE TITLE
Nested destructuring with default value fails

### ISSUE THREAD

**Issue by tomaskulich** [vacuumlabs/babel-plugin-extensible-destructuring#4]
var m = {"data":{"email":"teta@teta.sk"}}; 
     var {data:{email} = {}} = fromJS(m) // results in email being undefined

**Comment by hleumas** [comment]
@TheMarketka any progress?

**Comment by TheMarketka** [comment]
@hleumas please read gitter convo

**Comment by TheMarketka** [comment]
It really does not handle default values.
