### ISSUE TITLE
Using a variable in the destructuring is not working for immutables

### ISSUE THREAD

**Issue by jurom** [vacuumlabs/babel-plugin-extensible-destructuring#8]
Consider this example:
```
import {Iterable, fromJS} from 'immutable';
Iterable.prototype[Symbol.for('get')] = function(value) {return this.get(value) }

const t = fromJS({
    user: {
        0: {data: 'some data'}
    }
});

const id = 0;
const {user: {[id]: {data}}} = t;
```
This outputs a following error: `Cannot read property 'Symbol(get)' of undefined`

**Comment by hleumas** [comment]
@jurom does this apply to the newest version of plugin?

**Comment by jurom** [comment]
I heard @tomaskulich has fixed it today already

**Comment by tomaskulich** [comment]
https://github.com/vacuumlabs/babel-plugin-extensible-destructuring/pull/9

**Comment by tomaskulich** [comment]
Oh and btw, althought there actually was a bug in the plugin, the original snipet posted by @jurom won't work: note that 0 is converted to string within javascript object, but integer 0 is used for obtaining the value in the destructuring process.
